### PR TITLE
watch layout file too

### PR DESCRIPTION
**Pull request by bcomnes**
It would be nice if the `sitedown` cli watches the layout file, in addition to the md files it does now, so you can edit layouts and have everything regenerate automatically.

Whatcha think?

### CODE REVIEW

**Comment by ungoldman** [comment]
yeah sounds good. incremental builds would be good too

**Comment by ungoldman** [comment]
Oh hey @bcomnes! I thought this was an issue not a PR when I saw this a few days ago. If you want to rebase I'll merge next chance I get.

**Comment by bcomnes** [comment]
ok will do that

**Comment by bcomnes** [comment]
ok @ungoldman should be good to go.

**Comment by ungoldman** [comment]
released in https://github.com/ungoldman/sitedown/releases/v3.1.0

**Pull request merged**
